---
apiVersion: v1
kind: Service
metadata:
  name: cclookup-service
spec:
  type: NodePort
  selector:
    app: cclookup
  ports:
    - port: 4080
      targetPort: 4080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cclookup-deployment
  labels:
    app: cclookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cclookup
  template:
    metadata:
      labels:
        app: cclookup
    spec:
      containers:
      - name: cclookup
        image: registry.hub.docker.com/grajappan4401/cclookup:jenkinsbuild
        ports:
        - containerPort: 4080

    
